In [6]:
pip install mnist

Defaulting to user installation because normal site-packages is not writeable
  Using cached mnist-0.2.2-py2.py3-none-any.whl (3.5 kB)
Note: you may need to restart the kernel to use updated packages.


In [11]:
from PIL import Image
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import mnist as mnist
mnist.datasets_url = 'https://ossci-datasets.s3.amazonaws.com/mnist/'

print( mnist.__file__ )

C:\Users\avino\AppData\Roaming\Python\Python311\site-packages\mnist\__init__.py


In [18]:
#training variable
X_train = mnist.train_images()
y_train = mnist.train_labels()

In [19]:
X_test = mnist.test_images()
y_test = mnist.test_labels()

In [20]:
print("X Train ", X_train)
print("X Test ", X_test)
print("y Train ", y_train)


X Train  [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
X Test  [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 

In [27]:
print(X_train.ndim)
print(X_test.shape)

2
(10000, 784)


In [28]:
X_train = X_train.reshape((-1,28*28))
X_test = X_test.reshape((-1,28*28))

In [29]:
X_train = (X_train/256)
X_test = (X_test/256)

In [30]:
clf= MLPClassifier(solver="adam" , activation="relu", hidden_layer_sizes=(64,64))

In [31]:
clf.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [32]:
predictions = clf.predict(X_test)
acc = confusion_matrix(y_test,predictions)

In [33]:
print(acc)

[[ 971    0    0    1    0    1    3    1    3    0]
 [   0 1127    0    2    0    0    2    1    2    1]
 [   5    4 1004    4    0    0    4    4    7    0]
 [   0    0    4  992    0    4    0    2    1    7]
 [   0    1    2    1  967    0    1    2    1    7]
 [   3    0    0   12    3  865    4    0    4    1]
 [   2    2    0    2    6    5  938    0    3    0]
 [   1    3    8    2    1    0    0 1005    5    3]
 [   3    0    3    5    4    2    2    4  947    4]
 [   2    2    0    5   10    6    0    2    2  980]]


In [39]:
def accuracy(cm):
    diagonal = cm.trace()
    elements = cm.sum()
    return diagonal/elements

In [40]:
print("Accuracy of model: ", accuracy(acc))

Accuracy of model:  0.9796
